-- MySQL Script generated by MySQL Workbench
-- Sun Aug  9 21:53:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region` (
  `cod_region` INT(11) NOT NULL,
  `nombre_region` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_region`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ciudad` (
  `cod_ciudad` INT(11) NOT NULL,
  `nombre_ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `cod_region` INT(11) NOT NULL,
  PRIMARY KEY (`cod_ciudad`),
  INDEX `fk_Ciudad_region1` (`cod_region` ASC) VISIBLE,
  CONSTRAINT `fk_Ciudad_region1`
    FOREIGN KEY (`cod_region`)
    REFERENCES `mydb`.`region` (`cod_region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`periodo` (
  `cod_periodo` INT(11) NOT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`cod_periodo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_civil` (
  `cod_estado_civil` INT(11) NOT NULL,
  `nombre_estado` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_estado_civil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`estado_vigencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_vigencia` (
  `id_Estado_vigencia` INT NOT NULL,
  `desc_estado_vigencia` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Estado_vigencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brigadista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brigadista` (
  `rut` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `segundo_nombre` VARCHAR(100) NULL DEFAULT NULL,
  `apellido_paterno` VARCHAR(100) NULL DEFAULT NULL,
  `apellido_materno` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_nacimiento` VARCHAR(100) NULL DEFAULT NULL,
  `genero` VARCHAR(45) NULL DEFAULT NULL,
  `nivel_estudio` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `telefono_emergencia` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `enfermedades` TEXT NULL DEFAULT NULL,
  `cod_estado_civil` INT(11) NOT NULL,
  `cod_ciudad` INT(11) NOT NULL,
  `Asistencia_codAsistencia` INT NOT NULL,
  `Estado_vigencia_id_Estado_vigencia` INT NOT NULL,
  PRIMARY KEY (`rut`, `Estado_vigencia_id_Estado_vigencia`),
  INDEX `fk_Postulante_Estado_Civil1` (`cod_estado_civil` ASC) VISIBLE,
  INDEX `fk_postulante_Ciudad1` (`cod_ciudad` ASC) VISIBLE,
  INDEX `fk_brigadista_Estado_vigencia1_idx` (`Estado_vigencia_id_Estado_vigencia` ASC) VISIBLE,
  CONSTRAINT `fk_Postulante_Estado_Civil1`
    FOREIGN KEY (`cod_estado_civil`)
    REFERENCES `mydb`.`estado_civil` (`cod_estado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postulante_Ciudad1`
    FOREIGN KEY (`cod_ciudad`)
    REFERENCES `mydb`.`ciudad` (`cod_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_brigadista_Estado_vigencia1`
    FOREIGN KEY (`Estado_vigencia_id_Estado_vigencia`)
    REFERENCES `mydb`.`estado_vigencia` (`id_Estado_vigencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`estado_postulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_postulacion` (
  `idestado_postulacion` INT(11) NOT NULL,
  `nombre_estado` VARCHAR(100) NULL,
  PRIMARY KEY (`idestado_postulacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`postulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`postulacion` (
  `cod_postulacion` INT(11) NOT NULL,
  `codigo_postulacion` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_postulacion` DATE NULL DEFAULT NULL,
  `Postulante_RUT` VARCHAR(100) NOT NULL,
  `Periodo_idPeriodo` INT(11) NOT NULL,
  `ciudad_cod_ciudad` INT(11) NOT NULL,
  `estado_postulacion_idestado_postulacion` INT(11) NOT NULL,
  PRIMARY KEY (`cod_postulacion`, `ciudad_cod_ciudad`),
  INDEX `fk_Postulacion_Periodo1` (`Periodo_idPeriodo` ASC) VISIBLE,
  INDEX `fk_Postulacion_Postulante1` (`Postulante_RUT` ASC) VISIBLE,
  INDEX `fk_postulacion_ciudad1_idx` (`ciudad_cod_ciudad` ASC) VISIBLE,
  INDEX `fk_postulacion_estado_postulacion1_idx` (`estado_postulacion_idestado_postulacion` ASC) VISIBLE,
  CONSTRAINT `fk_Postulacion_Periodo1`
    FOREIGN KEY (`Periodo_idPeriodo`)
    REFERENCES `mydb`.`periodo` (`cod_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postulacion_Postulante1`
    FOREIGN KEY (`Postulante_RUT`)
    REFERENCES `mydb`.`brigadista` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postulacion_ciudad1`
    FOREIGN KEY (`ciudad_cod_ciudad`)
    REFERENCES `mydb`.`ciudad` (`cod_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postulacion_estado_postulacion1`
    FOREIGN KEY (`estado_postulacion_idestado_postulacion`)
    REFERENCES `mydb`.`estado_postulacion` (`idestado_postulacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`docu_postulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`docu_postulacion` (
  `idDocumentos` INT(11) NOT NULL,
  `nombre_documento` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_doc` DATE NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `postulacion_idPostulacion` INT(11) NOT NULL,
  PRIMARY KEY (`idDocumentos`),
  INDEX `fk_documentos_postulacion1_idx` (`postulacion_idPostulacion` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_postulacion1`
    FOREIGN KEY (`postulacion_idPostulacion`)
    REFERENCES `mydb`.`postulacion` (`cod_postulacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bodega` (
  `cod_bodega` INT NOT NULL,
  `desc_bodega` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_bodega`));


-- -----------------------------------------------------
-- Table `mydb`.`base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`base` (
  `cod_base` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `cod_region` INT(11) NOT NULL,
  `cod_bodega` INT(11) NOT NULL,
  `id_año` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_base`, `id_año`),
  INDEX `fk_Base_region1_idx` (`cod_region` ASC) VISIBLE,
  INDEX `fk_Base_BODEGA1_idx` (`cod_bodega` ASC) VISIBLE,
  CONSTRAINT `fk_Base_region1`
    FOREIGN KEY (`cod_region`)
    REFERENCES `mydb`.`region` (`cod_region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Base_BODEGA1`
    FOREIGN KEY (`cod_bodega`)
    REFERENCES `mydb`.`bodega` (`cod_bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuadrilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuadrilla` (
  `cod_cuadrilla` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `cod_base` INT NOT NULL,
  PRIMARY KEY (`cod_cuadrilla`),
  INDEX `idbase_idx` (`cod_base` ASC) VISIBLE,
  CONSTRAINT `idbase`
    FOREIGN KEY (`cod_base`)
    REFERENCES `mydb`.`base` (`cod_base`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`variables_emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`variables_emergencia` (
  `cod_variable` INT NOT NULL AUTO_INCREMENT,
  `temperatura` VARCHAR(45) NULL,
  `velocidad_viento` VARCHAR(45) NULL,
  `direccion_viento` VARCHAR(45) NULL,
  `humedad` VARCHAR(45) NULL,
  `presion` VARCHAR(45) NULL,
  `latitud_eme_actual` VARCHAR(45) NULL,
  `descp_otras_var` TEXT(500) NULL,
  `longuitud_eme_actual` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_variable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accion` (
  `cod_accion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_accion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emergencia` (
  `cod_emergencia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `ubicacion_actual` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_termino` DATE NULL,
  `km_afectados` INT NULL,
  `equipamiento` VARCHAR(45) NULL,
  `material_mayor` VARCHAR(45) NULL,
  `material_menor` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_emergencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`control_emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`control_emergencia` (
  `cod_control` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `ubicacion_actual` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `comentarios` VARCHAR(45) NULL,
  `km_afectados` INT NULL,
  `equipamiento` VARCHAR(45) NULL,
  `material_mayor` VARCHAR(45) NULL,
  `material_menor` VARCHAR(45) NULL,
  `cod_variable` INT NOT NULL,
  `cod_accion` INT NOT NULL,
  `cod_emergencia` INT NOT NULL,
  `fecha_control` DATE NULL,
  `hora` VARCHAR(45) NULL,
  `flag_vigencia` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_control`),
  INDEX `idvariable_idx` (`cod_variable` ASC) VISIBLE,
  INDEX `idaccion_idx` (`cod_accion` ASC) VISIBLE,
  INDEX `idemergencia_idx` (`cod_emergencia` ASC) VISIBLE,
  CONSTRAINT `idvariable`
    FOREIGN KEY (`cod_variable`)
    REFERENCES `mydb`.`variables_emergencia` (`cod_variable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idaccion`
    FOREIGN KEY (`cod_accion`)
    REFERENCES `mydb`.`accion` (`cod_accion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idemergencia`
    FOREIGN KEY (`cod_emergencia`)
    REFERENCES `mydb`.`emergencia` (`cod_emergencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estrategia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estrategia` (
  `codEstrategia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `procedimiento` VARCHAR(45) NULL,
  `equipamiento` VARCHAR(45) NULL,
  `cantidadCuadrillas` INT NULL,
  `cantidadBrigadistas` INT NULL,
  `epp` VARCHAR(45) NULL,
  `valoracion` INT NULL,
  `control_cod_control` INT NOT NULL,
  PRIMARY KEY (`codEstrategia`, `control_cod_control`),
  INDEX `fk_estrategia_control1_idx` (`control_cod_control` ASC) VISIBLE,
  CONSTRAINT `fk_estrategia_control1`
    FOREIGN KEY (`control_cod_control`)
    REFERENCES `mydb`.`control_emergencia` (`cod_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado_emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado_emergencia` (
  `codEestado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`codEestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emergencia_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emergencia_estado` (
  `cod_estado` INT NOT NULL,
  `cod_emergencia` INT NOT NULL,
  `fecha_entra_estado` DATE NULL,
  `fecha_sale_estado` DATE NULL,
  INDEX `idemergencia_idx` (`cod_emergencia` ASC) VISIBLE,
  CONSTRAINT `idestado`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `mydb`.`Estado_emergencia` (`codEestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idemergencia`
    FOREIGN KEY (`cod_emergencia`)
    REFERENCES `mydb`.`emergencia` (`cod_emergencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuadrilla_brigadista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuadrilla_brigadista` (
  `cod_cuadrilla` INT NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  INDEX `fk_Cuadrilla_has_Brigadista_Brigadista1_idx` (`rut` ASC) VISIBLE,
  INDEX `fk_Cuadrilla_has_Brigadista_Cuadrilla1_idx` (`cod_cuadrilla` ASC) VISIBLE,
  CONSTRAINT `fk_Cuadrilla_has_Brigadista_Cuadrilla1`
    FOREIGN KEY (`cod_cuadrilla`)
    REFERENCES `mydb`.`cuadrilla` (`cod_cuadrilla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuadrilla_has_Brigadista_Brigadista1`
    FOREIGN KEY (`rut`)
    REFERENCES `mydb`.`brigadista` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargos` (
  `cod_cargos` INT NOT NULL,
  `nombre_cargo` VARCHAR(45) NULL,
  `requisitos_cargo` VARCHAR(45) NULL,
  `sueldo_cargo` INT NULL,
  `cargoscol` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_cargos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especialidad` (
  `cod_esp` INT NOT NULL,
  `nombre_esp` VARCHAR(45) NULL,
  `bono_esp` INT NULL,
  `cod_cargos` INT NOT NULL,
  PRIMARY KEY (`cod_esp`),
  INDEX `fk_Especialidad_cargos1_idx` (`cod_cargos` ASC) VISIBLE,
  CONSTRAINT `fk_Especialidad_cargos1`
    FOREIGN KEY (`cod_cargos`)
    REFERENCES `mydb`.`cargos` (`cod_cargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cft` (
  `cod_cft` INT NOT NULL AUTO_INCREMENT,
  `nombre_cft` VARCHAR(45) NOT NULL,
  `correo_cft` VARCHAR(45) NOT NULL,
  `telefono_cft` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_cft`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sede_cft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sede_cft` (
  `cod_sede` INT NOT NULL AUTO_INCREMENT,
  `encargado_sede` VARCHAR(45) NOT NULL,
  `telefono_sede` VARCHAR(45) NOT NULL,
  `correo_sede` VARCHAR(45) NOT NULL,
  `direccion_sede` VARCHAR(45) NOT NULL,
  `cod_cft` INT NOT NULL,
  `cod_ciudad` INT(11) NOT NULL,
  PRIMARY KEY (`cod_sede`),
  INDEX `id_sede_idx` (`cod_cft` ASC) VISIBLE,
  INDEX `fk_sede_cft_ciudad1_idx` (`cod_ciudad` ASC) VISIBLE,
  CONSTRAINT `id_sede`
    FOREIGN KEY (`cod_cft`)
    REFERENCES `mydb`.`cft` (`cod_cft`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sede_cft_ciudad1`
    FOREIGN KEY (`cod_ciudad`)
    REFERENCES `mydb`.`ciudad` (`cod_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `cod_curs` INT NOT NULL,
  `nombre_curs` VARCHAR(45) NULL,
  `inicio_cur` VARCHAR(45) NOT NULL,
  `asistencia` INT NULL,
  `calificacion` VARCHAR(45) NULL,
  `recinto_certificado` VARCHAR(45) NULL,
  `estado_curso` VARCHAR(45) NULL,
  `cod_sede` INT NOT NULL,
  PRIMARY KEY (`cod_curs`, `inicio_cur`),
  INDEX `fk_cursos_sede_cft1_idx` (`cod_sede` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_sede_cft1`
    FOREIGN KEY (`cod_sede`)
    REFERENCES `mydb`.`sede_cft` (`cod_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`especialidad_brigadista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especialidad_brigadista` (
  `cod_esp` INT NOT NULL,
  `cod_cargos` INT NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  INDEX `fk_Especialidad_has_Brigadista_Brigadista1_idx` (`rut` ASC) VISIBLE,
  INDEX `fk_Especialidad_has_Brigadista_Especialidad1_idx` (`cod_esp` ASC, `cod_cargos` ASC) VISIBLE,
  CONSTRAINT `fk_Especialidad_has_Brigadista_Especialidad1`
    FOREIGN KEY (`cod_esp` , `cod_cargos`)
    REFERENCES `mydb`.`especialidad` (`cod_esp` , `cod_cargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Especialidad_has_Brigadista_Brigadista1`
    FOREIGN KEY (`rut`)
    REFERENCES `mydb`.`brigadista` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo` (
  `cod_tipo` INT NOT NULL,
  `DESC_TIPO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_tipo`));


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `cod_categoria` INT NOT NULL,
  `cod_tipo` INT NOT NULL,
  `desc_categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_categoria`),
  INDEX `FK_TIPO_CATEGORIA` (`cod_tipo` ASC) VISIBLE,
  CONSTRAINT `FK_TIPO_CATEGORIA`
    FOREIGN KEY (`cod_tipo`)
    REFERENCES `mydb`.`tipo` (`cod_tipo`)
    ON DELETE restrict
    ON UPDATE restrict);


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `cod_proveedor` INT NOT NULL,
  `nombre_proveedor` VARCHAR(100) NOT NULL,
  `rut_proveedor` VARCHAR(100) NOT NULL,
  `giro_proveedor` VARCHAR(100) NOT NULL,
  `direccion_proveedor` VARCHAR(100) NOT NULL,
  `contacto_proveedor` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cod_proveedor`));


-- -----------------------------------------------------
-- Table `mydb`.`datos_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_compra` (
  `cod_compra` INT NOT NULL,
  `cod_proveedor` INT NOT NULL,
  `numero_compra` INT NOT NULL,
  `despacho_compra` VARCHAR(100) NOT NULL,
  `forma_pago` VARCHAR(100) NOT NULL,
  `nota_compra` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`cod_compra`),
  INDEX `FK_PROVEEDOR_COMPRA` (`cod_proveedor` ASC) VISIBLE,
  CONSTRAINT `FK_PROVEEDOR_COMPRA`
    FOREIGN KEY (`cod_proveedor`)
    REFERENCES `mydb`.`proveedor` (`cod_proveedor`)
    ON DELETE restrict
    ON UPDATE restrict);


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `cod_marca` INT NOT NULL,
  `desc_marca` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_marca`));


-- -----------------------------------------------------
-- Table `mydb`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo` (
  `cod_modelo` INT NOT NULL,
  `desc_modelo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_modelo`));


-- -----------------------------------------------------
-- Table `mydb`.`talla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`talla` (
  `cod_talla` INT NOT NULL,
  `desc_talla` VARCHAR(100) NOT NULL,
  `valor_talla` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`cod_talla`));


-- -----------------------------------------------------
-- Table `mydb`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipo` (
  `cod_equipo` INT NOT NULL,
  `cod_talla` INT NULL,
  `cod_tipo` INT NOT NULL,
  `cod_modelo` INT NOT NULL,
  `cod_compra` INT NOT NULL,
  `cod_marca` INT NOT NULL,
  `cod_bodega` INT NULL DEFAULT NULL,
  `nombre_equipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_equipo`),
  INDEX `FK_EQUIPO_COMPRA` (`cod_compra` ASC) VISIBLE,
  INDEX `FK_EQUIPO_TIPO` (`cod_tipo` ASC) VISIBLE,
  INDEX `FK_MARCA_EQUIPO` (`cod_marca` ASC) VISIBLE,
  INDEX `FK_MODELO_EQUIPO` (`cod_modelo` ASC) VISIBLE,
  INDEX `FK_BODEGA_EQUIPO` (`cod_bodega` ASC) VISIBLE,
  INDEX `FK_TALLA_EQUIPO` (`cod_talla` ASC) VISIBLE,
  CONSTRAINT `FK_EQUIPO_COMPRA`
    FOREIGN KEY (`cod_compra`)
    REFERENCES `mydb`.`datos_compra` (`cod_compra`)
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `FK_EQUIPO_TIPO`
    FOREIGN KEY (`cod_tipo`)
    REFERENCES `mydb`.`tipo` (`cod_tipo`)
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `FK_MARCA_EQUIPO`
    FOREIGN KEY (`cod_marca`)
    REFERENCES `mydb`.`marca` (`cod_marca`)
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `FK_MODELO_EQUIPO`
    FOREIGN KEY (`cod_modelo`)
    REFERENCES `mydb`.`modelo` (`cod_modelo`)
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `FK_BODEGA_EQUIPO`
    FOREIGN KEY (`cod_bodega`)
    REFERENCES `mydb`.`bodega` (`cod_bodega`)
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `FK_TALLA_EQUIPO`
    FOREIGN KEY (`cod_talla`)
    REFERENCES `mydb`.`talla` (`cod_talla`)
    ON DELETE restrict
    ON UPDATE restrict);


-- -----------------------------------------------------
-- Table `mydb`.`estado_dev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_dev` (
  `COD_ESTADO` INT NOT NULL,
  `DESC_ESTADO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`COD_ESTADO`));


-- -----------------------------------------------------
-- Table `mydb`.`estado_equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_equipo` (
  `COD_ESTADO` INT NOT NULL,
  `COD_EQUIPO` INT NOT NULL,
  `FECHA_CAMBIO_ESTADO` DATE NOT NULL,
  PRIMARY KEY (`COD_ESTADO`, `COD_EQUIPO`),
  INDEX `FK_ESTADO_EQUIPO2` (`COD_EQUIPO` ASC) VISIBLE,
  CONSTRAINT `FK_ESTADO_EQUIPO`
    FOREIGN KEY (`COD_ESTADO`)
    REFERENCES `mydb`.`estado_dev` (`COD_ESTADO`)
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `FK_ESTADO_EQUIPO2`
    FOREIGN KEY (`COD_EQUIPO`)
    REFERENCES `mydb`.`equipo` (`cod_equipo`)
    ON DELETE restrict
    ON UPDATE restrict);


-- -----------------------------------------------------
-- Table `mydb`.`prestamo_devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prestamo_devolucion` (
  `rut` VARCHAR(12) NOT NULL,
  `cod_equipo` INT NOT NULL,
  `cod_prestamo` INT NOT NULL,
  `cod_estado` INT NULL,
  `fecha_prestamo` DATE NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`cod_prestamo`),
  INDEX `FK_PREST_DEV_ESTADO` (`cod_estado` ASC) VISIBLE,
  INDEX `FK_PREST_DEV_EQUIPO` (`cod_equipo` ASC) VISIBLE,
  INDEX `fk_PRESTAMO_DEVOLUCION_Brigadista1_idx` (`rut` ASC) VISIBLE,
  CONSTRAINT `FK_PREST_DEV_ESTADO`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `mydb`.`estado_dev` (`COD_ESTADO`)
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `FK_PREST_DEV_EQUIPO`
    FOREIGN KEY (`cod_equipo`)
    REFERENCES `mydb`.`equipo` (`cod_equipo`)
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `fk_PRESTAMO_DEVOLUCION_Brigadista1`
    FOREIGN KEY (`rut`)
    REFERENCES `mydb`.`brigadista` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`solicitud_equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solicitud_equipo` (
  `COD_SOLICITUD_EQ` INT NOT NULL,
  `RUT` VARCHAR(15) NOT NULL,
  `COD_EQUIPO` INT NOT NULL,
  `COD_PRESTAMO` INT NOT NULL,
  `COD_BODEGA` INT NOT NULL,
  `FECHA_SOLICITUD_EQ` DATE NOT NULL,
  `CANTIDAD_SOLICITUD` INT NOT NULL,
  `COD_CATEGORIA` INT NOT NULL,
  `Estrategia_codEstrategia` INT NOT NULL,
  PRIMARY KEY (`COD_SOLICITUD_EQ`),
  INDEX `FK_SOLICITUD_BODEGA` (`COD_BODEGA` ASC) VISIBLE,
  INDEX `FK_PREST_DEV_SOLICITUD` (`RUT` ASC, `COD_EQUIPO` ASC, `COD_PRESTAMO` ASC) VISIBLE,
  INDEX `fk_SOLICITUD_EQUIPO_CAREGORIA1_idx` (`COD_CATEGORIA` ASC) VISIBLE,
  INDEX `fk_SOLICITUD_EQUIPO_Estrategia1_idx` (`Estrategia_codEstrategia` ASC) VISIBLE,
  CONSTRAINT `FK_SOLICITUD_BODEGA`
    FOREIGN KEY (`COD_BODEGA`)
    REFERENCES `mydb`.`bodega` (`cod_bodega`)
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `FK_PREST_DEV_SOLICITUD`
    FOREIGN KEY (`RUT` , `COD_EQUIPO` , `COD_PRESTAMO`)
    REFERENCES `mydb`.`prestamo_devolucion` (`rut` , `cod_equipo` , `cod_prestamo`)
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `FK_SOLICITUD_CATEGORIA`
    FOREIGN KEY (`COD_CATEGORIA`)
    REFERENCES `mydb`.`categoria` (`cod_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITUD_EQUIPO_Estrategia1`
    FOREIGN KEY (`Estrategia_codEstrategia`)
    REFERENCES `mydb`.`estrategia` (`codEstrategia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`vida_util`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vida_util` (
  `cod_vida_util` INT NOT NULL,
  `cod_equipo` INT NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  PRIMARY KEY (`cod_vida_util`),
  INDEX `FK_EQUIPO_VIDA_UTIL` (`cod_equipo` ASC) VISIBLE,
  CONSTRAINT `FK_EQUIPO_VIDA_UTIL`
    FOREIGN KEY (`cod_equipo`)
    REFERENCES `mydb`.`equipo` (`cod_equipo`)
    ON DELETE restrict
    ON UPDATE restrict);


-- -----------------------------------------------------
-- Table `mydb`.`talla_brigadista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`talla_brigadista` (
  `cod_talla` INT NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  INDEX `fk_TALLA_has_Brigadista_Brigadista1_idx` (`rut` ASC) VISIBLE,
  INDEX `fk_TALLA_has_Brigadista_TALLA1_idx` (`cod_talla` ASC) VISIBLE,
  CONSTRAINT `fk_TALLA_has_Brigadista_TALLA1`
    FOREIGN KEY (`cod_talla`)
    REFERENCES `mydb`.`talla` (`cod_talla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TALLA_has_Brigadista_Brigadista1`
    FOREIGN KEY (`rut`)
    REFERENCES `mydb`.`brigadista` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`plan_nutricional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plan_nutricional` (
  `cod_plan_nutr` INT NOT NULL,
  `grasas` TINYINT NOT NULL,
  `lactosas` TINYINT NOT NULL,
  `alergias` VARCHAR(200) NULL,
  `alim_restrig` VARCHAR(200) NULL,
  `alim_recom` VARCHAR(200) NULL,
  `inicio_plan_nut` DATE NOT NULL,
  `fin_plan_nut` DATE NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`cod_plan_nutr`),
  INDEX `fk_PLANNUTRICIONAL_Brigadista1_idx` (`rut` ASC) VISIBLE,
  CONSTRAINT `fk_PLANNUTRICIONAL_Brigadista1`
    FOREIGN KEY (`rut`)
    REFERENCES `mydb`.`brigadista` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`control_nutricional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`control_nutricional` (
  `cod_control_nut` INT NOT NULL,
  `fecha_control_nut` DATE NOT NULL,
  `cod_plan_nut` INT NOT NULL,
  PRIMARY KEY (`cod_control_nut`),
  INDEX `fk_CONTROLNUTRICIONAL_PLANNUTRICIONAL1_idx` (`cod_plan_nut` ASC) VISIBLE,
  CONSTRAINT `fk_CONTROLNUTRICIONAL_PLANNUTRICIONAL1`
    FOREIGN KEY (`cod_plan_nut`)
    REFERENCES `mydb`.`plan_nutricional` (`cod_plan_nutr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accidente` (
  `cod_accidente` INT NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `inasistencia` TINYINT NOT NULL,
  `dias_inasit` INT NULL,
  `fecha_accident` DATE NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`cod_accidente`),
  INDEX `fk_ACCIDENTE_Brigadista1_idx` (`rut` ASC) VISIBLE,
  CONSTRAINT `fk_ACCIDENTE_Brigadista1`
    FOREIGN KEY (`rut`)
    REFERENCES `mydb`.`brigadista` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plan_ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plan_ejercicio` (
  `cod_plan_ejercicio` INT NOT NULL,
  `desc_trotes` VARCHAR(200) NULL,
  `desc_ejer_musc` VARCHAR(200) NULL,
  `desc_otros` VARCHAR(200) NULL,
  `inic_plan_ejer` DATE NOT NULL,
  `fin_plan_ejer` DATE NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`cod_plan_ejercicio`),
  INDEX `fk_PLANEJERCICIOS_Brigadista1_idx` (`rut` ASC) VISIBLE,
  CONSTRAINT `fk_PLANEJERCICIOS_Brigadista1`
    FOREIGN KEY (`rut`)
    REFERENCES `mydb`.`brigadista` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`control_ejercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`control_ejercicios` (
  `cod_control_ejercicios` INT NOT NULL,
  `cod_fecha_control_ejer` DATE NOT NULL,
  `cod_plan_ejercicio` INT NOT NULL,
  PRIMARY KEY (`cod_control_ejercicios`),
  INDEX `fk_CONTROLEJERCICIOS_PLANEJERCICIOS1_idx` (`cod_plan_ejercicio` ASC) VISIBLE,
  CONSTRAINT `fk_CONTROLEJERCICIOS_PLANEJERCICIOS1`
    FOREIGN KEY (`cod_plan_ejercicio`)
    REFERENCES `mydb`.`plan_ejercicio` (`cod_plan_ejercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`examen` (
  `cod_examen` INT NOT NULL,
  `nombre_examen` VARCHAR(45) NULL,
  `tipo_examen` VARCHAR(45) NULL,
  `parametronorrmalidad_examen` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_examen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sede_achs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sede_achs` (
  `cod_sede` INT NOT NULL,
  `nombre_sede` VARCHAR(45) NULL,
  `cod_ciudad` INT(11) NOT NULL,
  PRIMARY KEY (`cod_sede`),
  INDEX `fk_SEDE_ACHS_ciudad1_idx` (`cod_ciudad` ASC) VISIBLE,
  CONSTRAINT `fk_SEDE_ACHS_ciudad1`
    FOREIGN KEY (`cod_ciudad`)
    REFERENCES `mydb`.`ciudad` (`cod_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `rut_medico` VARCHAR(12) NOT NULL,
  `nombre_medico` VARCHAR(45) NULL,
  `nacimiento_medico` DATE NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`rut_medico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seguir_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seguir_estado` (
  `cod_estado` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `situacion_estado` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ficha_medica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ficha_medica` (
  `cod_ficha` INT NOT NULL,
  `peso_ficha` VARCHAR(45) NULL,
  `estatura_ficha` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `fecha_ficha` DATE NULL,
  `cod_sede` INT NOT NULL,
  `rut_medico` VARCHAR(12) NOT NULL,
  `rut_paciente` VARCHAR(12) NOT NULL,
  `cod_estado` INT NOT NULL,
  `rut` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`cod_ficha`),
  INDEX `fk_FICHA_MEDICA_SEDE_ACHS1_idx` (`cod_sede` ASC) VISIBLE,
  INDEX `fk_FICHA_MEDICA_MEDICO1_idx` (`rut_medico` ASC) VISIBLE,
  INDEX `fk_FICHA_MEDICA_SEGUIR_ESTADO1_idx` (`cod_estado` ASC) VISIBLE,
  INDEX `fk_FICHA_MEDICA_Brigadista1_idx` (`rut` ASC) VISIBLE,
  CONSTRAINT `fk_FICHA_MEDICA_SEDE_ACHS1`
    FOREIGN KEY (`cod_sede`)
    REFERENCES `mydb`.`sede_achs` (`cod_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FICHA_MEDICA_MEDICO1`
    FOREIGN KEY (`rut_medico`)
    REFERENCES `mydb`.`medico` (`rut_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FICHA_MEDICA_SEGUIR_ESTADO1`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `mydb`.`seguir_estado` (`cod_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FICHA_MEDICA_Brigadista1`
    FOREIGN KEY (`rut`)
    REFERENCES `mydb`.`brigadista` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`realiza_examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`realiza_examen` (
  `cod_ficha` INT NOT NULL,
  `cod_examen` INT NOT NULL,
  `fecha_examen` VARCHAR(45) NULL,
  `rut_medico` VARCHAR(12) NOT NULL,
  `cod_doc_salud` INT NULL,
  INDEX `fk_FICHA_MEDICA_has_EXAMEN_EXAMEN1_idx` (`cod_examen` ASC) VISIBLE,
  INDEX `fk_FICHA_MEDICA_has_EXAMEN_FICHA_MEDICA1_idx` (`cod_ficha` ASC) VISIBLE,
  UNIQUE INDEX `FICHA_MEDICA_COD_FICHA_UNIQUE` (`cod_ficha` ASC) VISIBLE,
  INDEX `fk_REALIZA_EXAMEN_MEDICO1_idx` (`rut_medico` ASC) VISIBLE,
  CONSTRAINT `fk_FICHA_MEDICA_has_EXAMEN_FICHA_MEDICA1`
    FOREIGN KEY (`cod_ficha`)
    REFERENCES `mydb`.`ficha_medica` (`cod_ficha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FICHA_MEDICA_has_EXAMEN_EXAMEN1`
    FOREIGN KEY (`cod_examen`)
    REFERENCES `mydb`.`examen` (`cod_examen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REALIZA_EXAMEN_MEDICO1`
    FOREIGN KEY (`rut_medico`)
    REFERENCES `mydb`.`medico` (`rut_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salud_doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salud_doc` (
  `cod_doc` INT NOT NULL,
  `descripcion_doc` VARCHAR(45) NULL,
  `ruta_serc_doc` VARCHAR(45) NULL,
  `titulo_doc` VARCHAR(45) NULL,
  `archivo_doc` INT NULL,
  `cod_doc_salud` INT NOT NULL,
  PRIMARY KEY (`cod_doc`),
  INDEX `fk_SALUD_DOC_REALIZA_EXAMEN1_idx` (`cod_doc_salud` ASC) VISIBLE,
  CONSTRAINT `fk_SALUD_DOC_REALIZA_EXAMEN1`
    FOREIGN KEY (`cod_doc_salud`)
    REFERENCES `mydb`.`realiza_examen` (`cod_doc_salud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pertenece_a`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pertenece_a` (
  `BRIGADA_id_brigada` INT NOT NULL,
  `USUARIO_id_usu` INT NOT NULL,
  `temporada` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posee` (
  `USUARIO_id_usu` INT NOT NULL,
  `ESPECIALIDAD_id_especialidad` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesor` (
  `cod_profesor` INT NOT NULL,
  `rut_profesor` VARCHAR(12) NOT NULL,
  `nombre_profesor` VARCHAR(45) NOT NULL,
  `apellido_profesor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`version_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`version_curso` (
  `cod_version_curso` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_termino` DATE NOT NULL,
  `cod_profesor` INT NOT NULL,
  `cod_curs` INT NOT NULL,
  `sede_cft_cod_sede` INT NOT NULL,
  PRIMARY KEY (`cod_version_curso`, `sede_cft_cod_sede`),
  INDEX `id_profesor_idx` (`cod_profesor` ASC) VISIBLE,
  INDEX `fk_version_curso_Cursos1_idx` (`cod_curs` ASC) VISIBLE,
  INDEX `fk_version_curso_sede_cft1_idx` (`sede_cft_cod_sede` ASC) VISIBLE,
  CONSTRAINT `id_profesor`
    FOREIGN KEY (`cod_profesor`)
    REFERENCES `mydb`.`profesor` (`cod_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_version_curso_Cursos1`
    FOREIGN KEY (`cod_curs`)
    REFERENCES `mydb`.`cursos` (`cod_curs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_version_curso_sede_cft1`
    FOREIGN KEY (`sede_cft_cod_sede`)
    REFERENCES `mydb`.`sede_cft` (`cod_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`competencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`competencia` (
  `cod_competencia` INT NOT NULL AUTO_INCREMENT,
  `nombre_competencia` VARCHAR(45) NOT NULL,
  `detalles_competencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_competencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tiene_comp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tiene_comp` (
  `cod_competencia` INT NOT NULL,
  `cod_curs` INT NOT NULL,
  INDEX `id_competencia_idx` (`cod_competencia` ASC) VISIBLE,
  CONSTRAINT `id_competencia`
    FOREIGN KEY (`cod_competencia`)
    REFERENCES `mydb`.`competencia` (`cod_competencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tiene_comp_Cursos1`
    FOREIGN KEY (`cod_curs`)
    REFERENCES `mydb`.`cursos` (`cod_curs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inscribe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inscribe` (
  `rut` VARCHAR(12) NOT NULL,
  `cod_version_curso` INT NOT NULL,
  INDEX `fk_Brigadista_has_version_curso_version_curso1_idx` (`cod_version_curso` ASC) VISIBLE,
  INDEX `fk_Brigadista_has_version_curso_Brigadista1_idx` (`rut` ASC) VISIBLE,
  CONSTRAINT `fk_Brigadista_has_version_curso_Brigadista1`
    FOREIGN KEY (`rut`)
    REFERENCES `mydb`.`brigadista` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Brigadista_has_version_curso_version_curso1`
    FOREIGN KEY (`cod_version_curso`)
    REFERENCES `mydb`.`version_curso` (`cod_version_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`otorga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`otorga` (
  `cod_curs` INT NOT NULL,
  `cod_esp` INT NOT NULL,
  `cod_cargos` INT NOT NULL,
  INDEX `fk_Cursos_has_Especialidad_Especialidad1_idx` (`cod_esp` ASC, `cod_cargos` ASC) VISIBLE,
  INDEX `fk_Cursos_has_Especialidad_Cursos1_idx` (`cod_curs` ASC) VISIBLE,
  CONSTRAINT `fk_Cursos_has_Especialidad_Cursos1`
    FOREIGN KEY (`cod_curs`)
    REFERENCES `mydb`.`cursos` (`cod_curs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_has_Especialidad_Especialidad1`
    FOREIGN KEY (`cod_esp` , `cod_cargos`)
    REFERENCES `mydb`.`especialidad` (`cod_esp` , `cod_cargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuadrilla_en_emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuadrilla_en_emergencia` (
  `estrategia_codEstrategia` INT NOT NULL,
  `estrategia_control_cod_control` INT NOT NULL,
  `cuadrilla_cod_cuadrilla` INT NOT NULL,
  `fecha_inicio_asignación` VARCHAR(45) NULL,
  `fecha_termino_asignación` VARCHAR(45) NULL,
  PRIMARY KEY (`estrategia_codEstrategia`, `estrategia_control_cod_control`, `cuadrilla_cod_cuadrilla`),
  INDEX `fk_estrategia_has_cuadrilla_cuadrilla1_idx` (`cuadrilla_cod_cuadrilla` ASC) VISIBLE,
  INDEX `fk_estrategia_has_cuadrilla_estrategia1_idx` (`estrategia_codEstrategia` ASC, `estrategia_control_cod_control` ASC) VISIBLE,
  CONSTRAINT `fk_estrategia_has_cuadrilla_estrategia1`
    FOREIGN KEY (`estrategia_codEstrategia` , `estrategia_control_cod_control`)
    REFERENCES `mydb`.`estrategia` (`codEstrategia` , `control_cod_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estrategia_has_cuadrilla_cuadrilla1`
    FOREIGN KEY (`cuadrilla_cod_cuadrilla`)
    REFERENCES `mydb`.`cuadrilla` (`cod_cuadrilla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sede` (
  `id_sede` INT NOT NULL AUTO_INCREMENT,
  `encargado_sede` VARCHAR(45) NOT NULL,
  `telefono_sede` VARCHAR(45) NOT NULL,
  `correo_sede` VARCHAR(45) NOT NULL,
  `direccion_sede` VARCHAR(45) NOT NULL,
  `id_cft` INT NOT NULL,
  `id_ciudad` INT NOT NULL,
  PRIMARY KEY (`id_sede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre_curso` VARCHAR(45) NOT NULL,
  `id_sede` INT NOT NULL,
  `temario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `id_sede_idx` (`id_sede` ASC) VISIBLE,
  CONSTRAINT `id_sede`
    FOREIGN KEY (`id_sede`)
    REFERENCES `mydb`.`sede` (`id_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tiene` (
  `id_curso` INT NOT NULL,
  `id_competencia` INT NOT NULL,
  INDEX `id_curso_idx` (`id_curso` ASC) VISIBLE,
  CONSTRAINT `id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
